---  
access_switches: 
  - {hostname: deg-sw1, secret: s3cReT$sw, access_vlan: 2208, ip_addr: 1.1.1.51, default_gateway: 1.1.1.1, snmp_community: $nMPComm}
  - {hostname: deg-sw2, secret: s3cReT$sw, access_vlan: 2208, ip_addr: 1.1.2.51, default_gateway: 1.1.2.1, snmp_community: $nMPComm}
  - {hostname: deg-sw3, secret: s3cReT$sw, access_vlan: 2208, ip_addr: 1.1.3.51, default_gateway: 1.1.3.1, snmp_community: $nMPComm}
  - {hostname: deg-sw4, secret: s3cReT$sw, access_vlan: 2208, ip_addr: 1.1.4.51, default_gateway: 1.1.4.1, snmp_community: $nMPComm}
  - {hostname: deg-sw5, secret: s3cReT$sw, access_vlan: 2208, ip_addr: 1.1.5.51, default_gateway: 1.1.5.1, snmp_community: $nMPComm}
