---
- name: Arista Trunking
  hosts: arista

  tasks:
    - name: Set Ethernet6 to trunk
      eos_switchport: name=Ethernet6 mode=trunk trunk_native_vlan=1 trunk_allowed_vlans=2200,2201,2202
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https

