- name: Cisco IOS testing
  hosts: cisco
  gather_facts: False
  
  tasks:
    - name: File Transfer
      cisco_file_transfer:
        source_file="/home/mdegasperis/ANSIBLE/cisco_logcon.txt"
        dest_file=cisco_logcon.txt
        overwrite=true
        enable_scp=true
        host={{ host }}
        port={{ port }}
        username={{ username }}
        password={{ password }}
