---
- name: Change Ethernet6 interface
  hosts: arista

  tasks:
    - name: Change Ethernet6 Description
      eos_interface: name=Ethernet6 description="*** IN USE ***"
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https

    - name: Change Ethernet6 Access VLAN
      eos_switchport: name=Ethernet6 mode=access access_vlan=2202
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https

